#!/bin/sh
make clean;
if [ $1 = 'stratixv' ]
then
    make EXTRA_CFLAGS=-DSTRATIXV;
elif [ $1 = 'stratix10' ]
then
    make EXTRA_CFLAGS=-DSTRATIX10;
elif [ $1 = 'arria10' ]
then
    make EXTRA_CFLAGS=-DARRIA10;
elif [ $1 = 'cyclone10' ]
then
    make EXTRA_CFLAGS=-DCYCLONE10;
else
    echo "Unsupported Device"
    exit
fi
if [ `lsmod | grep -o altera_dma` ]
then
    ./unload
fi
./altera_dma_load


